/obj/item/storage/backpack/duffelbag/syndie/mime/PopulateContents()
	new /obj/item/modular_computer/pda/mime(src)
	new /obj/item/clothing/under/rank/civilian/mime(src)
	new /obj/item/clothing/shoes/laceup(src)
	new /obj/item/clothing/mask/gas/mime(src)
	new /obj/item/clothing/suit/toggle/suspenders(src)
	new /obj/item/clothing/gloves/color/white(src)
	new /obj/item/clothing/head/beret/frenchberet(src)
	new /obj/item/stamp/mime(src)
	new /obj/item/reagent_containers/cup/glass/bottle/bottleofnothing(src)
	new /obj/item/book/granter/action/spell/mime/mimery(src)
	new /obj/item/storage/box/survival/hug/black(src)
