/obj/item/storage/portable_chem_mixer/fully_stocked/PopulateContents()
	new /obj/item/reagent_containers/cup/bottle/aluminium(src)
	new /obj/item/reagent_containers/cup/bottle/bromine(src)
	new /obj/item/reagent_containers/cup/bottle/carbon(src)
	new /obj/item/reagent_containers/cup/bottle/chlorine(src)
	new /obj/item/reagent_containers/cup/bottle/copper(src)
	new /obj/item/reagent_containers/cup/bottle/ethanol(src)
	new /obj/item/reagent_containers/cup/bottle/fluorine(src)
	new /obj/item/reagent_containers/cup/bottle/hydrogen(src)
	new /obj/item/reagent_containers/cup/bottle/iodine(src)
	new /obj/item/reagent_containers/cup/bottle/iron(src)
	new /obj/item/reagent_containers/cup/bottle/lithium(src)
	new /obj/item/reagent_containers/cup/bottle/mercury(src)
	new /obj/item/reagent_containers/cup/bottle/nitrogen(src)
	new /obj/item/reagent_containers/cup/bottle/oxygen(src)
	new /obj/item/reagent_containers/cup/bottle/phosphorus(src)
	new /obj/item/reagent_containers/cup/bottle/potassium(src)
	new /obj/item/reagent_containers/cup/bottle/radium(src)
	new /obj/item/reagent_containers/cup/bottle/silicon(src)
	new /obj/item/reagent_containers/cup/bottle/sodium(src)
	new /obj/item/reagent_containers/cup/bottle/stable_plasma(src)
	new /obj/item/reagent_containers/cup/bottle/sugar(src)
	new /obj/item/reagent_containers/cup/bottle/sulfur(src)
	new /obj/item/reagent_containers/cup/bottle/sacid(src)
	new /obj/item/reagent_containers/cup/bottle/water(src)
	new /obj/item/reagent_containers/cup/bottle/welding_fuel(src)
	update_contents()
